### ISSUE TITLE
Feature request: Add output folder preset

### ISSUE THREAD

**Issue by ciraben** [jasyip/musescore-scraper#1]
Currently, scorescraper saves files to the current working directory. It would be sooo nice to be able to alt-tab over to my terminal app when I find a score I like, call `scorescraper [paste URL]` and feel confident the score will end up in my `sheet_music` folder, regardless of what I was last using my terminal session for.

I understand that `scorescraper -o path/to/dir URL` works for this. But imagine running `scorescraper -O path/to/dir` once, and then never having to worry about it again! It would be so sleek!

✨Love this project, btw. This tool has brought me a lot of joy and convenience✨

**Comment by jaschiu** [comment]
Hi, I haven't touched this project in so long and I realized after my last update, there are better alternatives that have even more features. I'm not sure if these alternatives are guaranteed to work as they abuse some holes in MuseScore's API, mine could fall apart if they change it (Mine makes use of the HTML and Javascript). I will probably archive this now as this popped up in my dashboard--should have been archived long ago.

The alternatives to this project most likely do not have that feature--you can make a simple shell script to do that for you. I'll just write this below without actually testing it:

```bash
#!/usr/bin/env bash
local dir="[insert desired path]"
musescraper -o  "$dir" "$@"
```

If you prefer that your script reads the path from a file in the same working directory:
```bash
#!/usr/bin/env bash
musescraper -o  `cat "[insert filename]"` "$@"
```

Thanks for reminding about this old project,brings back memories. Let me know if you need anything else--hopefully you can still comment/make an issue on an archived repository.

Edit: I guess comments/new issues are disabled in archived repositories, but I wish you luck!
